default: &default
  adapter: mysql2
  encoding: utf8mb4
  collation: utf8mb4_unicode_ci
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: ENV['MYSQL_USERNAME']
  password: ENV['MYSQL_PASSWORD']
  host: ENV['MYSQL_HOST']
  ssl_mode: verify_identity
  sslca: "/etc/ssl/certs/ca-certificates.crt"

development:
  <<: *default
  database: mundo_de_princesa_dev


test:
  <<: *default
  database: mundo_de_princesa_teste

production:
  <<: *default
  database: ENV['MYSQL_PROD_DB']
